[mypy]
# Вказуємо папки та файли, які слід виключити з перевірки
;exclude = ^src/database/migrations/.*|^src/config/.*|^src/tests/.*|^src/database/session_postgresql.py
exclude = src/database/migrations/.*|src/config/.*|src/tests/.*|src/database/session_postgresql.py$

# Вимкнути певні типи помилок
disable_error_code = misc

# Вказуємо версію Python для mypy
python_version = 3.10

# Ігноруємо відсутні імпорти
ignore_missing_imports = True

# Включити суворі перевірки
strict = True

# Попередження про невикористовувані ігнорування
warn_unused_ignores = True

# Попередження про зайві приведення типів
warn_redundant_casts = True

# Заборона на функції без типів
disallow_untyped_defs = True
