from enum import Enum


class StripePaymentMethod(Enum):
    ACSS_DEBIT = "acss_debit"
    AFFIRM = "affirm"
    AFTERPAY_CLEARPAY = "afterpay_clearpay"
    ALIPAY = "alipay"
    ALMA = "alma"
    AMAZON_PAY = "amazon_pay"
    AU_BECS_DEBIT = "au_becs_debit"
    BACS_DEBIT = "bacs_debit"
    BANCONTACT = "bancontact"
    BLIK = "blik"
    BOLETO = "boleto"
    CARD = "card"
    CASHAPP = "cashapp"
    CUSTOMER_BALANCE = "customer_balance"
    EPS = "eps"
    FPX = "fpx"
    GIROPAY = "giropay"
    GRABPAY = "grabpay"
    IDEAL = "ideal"
    KAKAO_PAY = "kakao_pay"
    KLARNA = "klarna"
    KONBINI = "konbini"
    KR_CARD = "kr_card"
    LINK = "link"
    MOBILEPAY = "mobilepay"
    MULTIBANCO = "multibanco"
    NAVER_PAY = "naver_pay"
    OXXO = "oxxo"
    P24 = "p24"
    PAY_BY_BANK = "pay_by_bank"
    PAYCO = "payco"
    PAYNOW = "paynow"
    PAYPAL = "paypal"
    PIX = "pix"
    PROMPTPAY = "promptpay"
    REVOLUT_PAY = "revolut_pay"
    SAMSUNG_PAY = "samsung_pay"
    SEPA_DEBIT = "sepa_debit"
    SOFORT = "sofort"
    SWISH = "swish"
    TWINT = "twint"
    US_BANK_ACCOUNT = "us_bank_account"
    WECHAT_PAY = "wechat_pay"
    ZIP = "zip"
